'use strict';
var path = require('path');

var spv = require('..');
var Pool = spv.Pool;
var Wallet = spv.Wallet;


var pool = new Pool({ relay: false });
pool.on('chain-progress', function(progress) {
    var height = pool.chain.index.lastHeight;
    console.log('syncProgress:', progress, 'height:', height,
      'estimatedHeight', pool.chain.estimatedBlockHeight());
});
pool.connect();

pool.once('chain-full', finish);
process.once('SIGINT', finish);

var hasRun = 0;
function finish() {
  if (hasRun)
    return;
  hasRun = 1;

  console.log('Done...');
  var chain = '// Autogenerated by scripts/spvnode.js\n' +
    'module.exports = ' +
    JSON.stringify(pool.chain.toJSON(), null, 2) + '\n';
  var file = path.resolve(__dirname,'..','lib','data','index.js');
  require('fs').writeFileSync(file, chain);
  pool.disconnect();
}
